name: splitwithfriends
description: "Manage friends in split with me"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Internacionalización ---
  flutter_localizations:
    sdk: flutter

  # CAMBIO AQUÍ: Actualizado a la versión que pide tu Flutter
  intl: ^0.20.2

  # --- Paquetes base ---
  cupertino_icons: ^1.0.8

  # --- Paquetes de red/estado ---
  http: ^1.1.0
  collection: ^1.18.0
  provider: ^6.1.1

  # --- Base de datos local ---
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generador de código
  build_runner: ^2.4.6
  isar_generator: ^3.1.0

  # Lints
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true